### ISSUE TITLE
Hash routing

### ISSUE THREAD

**Issue by motss** [ionic-team/stencil-router#10]
Few questions:

1. Does `stencil-router` listen to route that contains hash (`#`)?
2. If yes, how to do `scrollIntoView` with hash with `stencil-router`?

**Comment by alua1612** [comment]
@motss  how did you do this? I have the same problem

**Comment by Hiunkeru** [comment]
Use "historyType='hash'

<stencil-router historyType={'hash'}>
            <stencil-route-switch scrollTopOffset={0}>
              <stencil-route
                url='/url'
                component='my-component'
                exact={true} /
                componentProps={{
                  prop1: this.myprop1,
                  prop2: this.myprop2,
                }}
              />
