### ISSUE TITLE
Stencil config includes demos

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil-router#12]
Am I correct in thinking the config shouldn't include our demos?

https://github.com/ionic-team/stencil-router/blob/master/stencil.config.js

**Comment by jthoms1** [comment]
Ya, unfortunately not an easy way to setup test demos in this repo without including them in the stencil config.

**Comment by chrisweight** [comment]
Confirmed this, it's currently breaking tests unfortunately as it looks like the test-demo components are included in the `collection-manifest.json` in dist on compile

```
   {
      "components": [
        "test-app"
      ]
    },
    {
      "components": [
        "test-demo-four"
      ]
    },
    {
      "components": [
        "test-demo-six"
      ]
    },
    {
      "components": [
        "test-demo-three"
      ]
    }
```

**Comment by chrisweight** [comment]
If I make `generateDistribution: false` in `stencil.config.js` this ^^ obviously doesn't happen ...

**Comment by jgw96** [comment]
Closing this as the demo components do not seem to be included in the config anymore. Thanks!
