### ISSUE TITLE
componentProps in starter-app not working

### ISSUE THREAD

**Issue by gregorypratt** [ionic-team/stencil-router#19]
```jsx
<stencil-router id="app-content">
  <stencil-route url="/" component="first-name" componentProps={{ first: 'Stencil' }} exact={true} />
  <stencil-route url="/second" component="second-name" componentProps={{ first: 'Stencil2' }} />
</stencil-router>
```

I would expect the above to pass the value of the `first` prop down to `<first-name/>` and `<second-name/>` but nothing seems to happen. The prop is `undefined` on render.

If I use the components outside of the router they work correctly.

**Comment by jthoms1** [comment]
https://github.com/ionic-team/stencil-router/blob/master/src/components/__tests__/test-app.tsx#L56
https://github.com/ionic-team/stencil-router/blob/master/src/components/__tests__/test-demo-three.tsx#L9

This should work please ensure you are using the latest which is 0.0.17. Above is an example about usage.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue I will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!
