### ISSUE TITLE
Add router hooks

### ISSUE THREAD

**Issue by ansarizafar** [ionic-team/stencil-router#2]
Please add before and after router hooks.

**Comment by cdiaz** [comment]
This is essential to include policies such as canActivate, or role-based access

**Comment by jthoms1** [comment]
Instead of using hooks, I am in the process of changing so that routes have a renderRoute function that can be used to for guards.  This would be very similar to the approach of react-router. https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by jthoms1** [comment]
You should now be able write the following code to implement auth policies in routes. We now allow you to use a routeRender function within stencil-routes.  Within this function you can check if the user is authenticated using your authSystem of choice.

If the user IS NOT authenticated then use the stencil-router-redirect to send the user to a login page.  If the user IS authenicated then render the component that is private.
```js
<stencil-route url="/" exact={true} routeRender={
  (props: { [key: string]: any}) => {
    const isAuthenticationed = authSystem.isAuthenticated();
    if (!isAuthenticated) {
      <stencil-router-redirect url="/login" />
    }
    return <account-info></account-info>;
  }
}></stencil-route>
```
