### ISSUE TITLE
Implement a router-switch (feature)

### ISSUE THREAD

**Issue by foreggs** [ionic-team/stencil-router#22]
Hi, I have been using stencil for a few days now for my side project and it's awesome so far!.  I feel like there is a need to implement a route switch that only renders one of the given routes, just like e.g. this one: [React Router Switch](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md)

**Comment by jthoms1** [comment]
There currently is an equivalent called router group, but I agree that we should add a switch. https://github.com/ionic-team/stencil-router/blob/ea3a8d526255ad2ad1fe3dc4f70048a9c220486b/src/components/__tests__/test-demo-six.tsx#L16

**Comment by jthoms1** [comment]
Commit 0b9d7cc97ca0e043cc39cf382fbed75628b8e08a fixes this issue.
