### ISSUE TITLE
componentProps and RouterHistory are not passed to target component

### ISSUE THREAD

**Issue by nowzig** [ionic-team/stencil-router#24]
The defined componentProps in a <stencil-route> are not passed to the component.

Also the RouterHistory is not passed to the component.

When testing with routeRender function everything is there.

I am using stencil 0.0.8-5.

**Comment by jthoms1** [comment]
https://github.com/ionic-team/stencil-router/blob/master/src/components/__tests__/test-demo-three.tsx#L7
Ensure you are using the latest 0.0.17.  history and props should be available, refer to the example linked above.
