### ISSUE TITLE
Is there anything similar to the basename of React Router?

### ISSUE THREAD

**Issue by hufan-akari** [ionic-team/stencil-router#26]
https://github.com/ionic-team/stencil-router/blob/37c9dcec01724f7bdd4e8bfbdbc7f0d99571b2ee/src/components/router/router.tsx#L14

I found the `root` prop in `src/components/router/router.tsx`
Is it as same as the basename of React Router?
How to use it?

**Comment by jthoms1** [comment]
You are correct it should act the same as basename in React Router.  I badly need to have some documentation for a lot of these optional props.

**Comment by mlynch** [comment]
In my local test, I don't think root property is working properly. Working on a fix

**Comment by mlynch** [comment]
Okay root should be applied now for links, redirects, and routes
