### ISSUE TITLE
Routing doesn't work if deploy is in a subfolder.

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/stencil-router#29]
_From @Gafilipoie on February 15, 2018 21:46_

**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I'm running a build with npm run build command which outputs the folder www.
I'm deploying the folder to a server (xampp or heroku) and the routing doesn't work.
User visits http://localhost/www/,
then click the Alerts link,
it directs him to http://localhost/alerts/

**Expected behavior:**
If a user visits http://localhost/www/,
then click the Alerts link,
it should direct him to http://localhost/www/alerts/

**Steps to reproduce:**
http://localhost/www/ works, but if I click the Alerts link the url changes to http://localhost/alerts/ and that returns a 404 page not found.
It's like the routing doesn't work when the website is in a subfolder.

**Related code:**

```tsx
<stencil-route-link url="/alerts" activeClass="active" exact={true}> Alerts </stencil-route-link>
<stencil-router id="router"><stencil-route  url={['/', '/alerts']} component="alerts-page" exact={true} > </stencil-route>
```

**Other information:**

_Copied from original issue: ionic-team/stencil#541_

**Comment by jthoms1** [comment]
There is a prop available for router that sets the `root`.  By default it is set to '/'.  In this particular instance you would set it to `'/www'`.
```jsx
<stencil-router id="router" root="/www">
  <stencil-route url={['/', '/alerts']} component="alerts-page" exact={true} />
</stencil-router>
```

**Comment by Gafilipoie** [comment]
I've added it, but no changes.
The same behavior exists.
