### ISSUE TITLE
Routes need to be checked for matches again once a group has rendered in the dom

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil-router#41]
When using `group` and `groupIndex` to implement a wildcard route, the first load will match both the `/` route and the catch all route. Interestingly, after navigating to a different route, things work correctly.

- Correct behavior would be to only match on the root route the first time a page loads
- Can be reproduced with the latest master branch of the stencil site

**Comment by jthoms1** [comment]
Commit 2a9ab61 fixes this issue.
