### ISSUE TITLE
Defaults to bottom of the page on page change

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil-router#46]
Steps to reproduce the issue:

1. Navigate to https://stenciljs.com/resources
2. Scroll to the bottom
3. Click the PWA link in the header

Observe the scroll position is not reset. You're at the bottom of the `pwa` page. FWIW, this behavior seems inconsistent to me. I cannot pinpoint exactly what the problem is, but I also haven't really tried 😆 

Thanks,
Dan

**Comment by jthoms1** [comment]
Hmm, can't reproduce.  What browser are you using?

**Comment by danbucholtz** [comment]
Every browser. Here is a video of the repro case.

https://drive.google.com/open?id=1l4pRCQP_BjTA9R-DlTsmJnYQlGmfoQ9L

Thanks,
Dan

**Comment by jthoms1** [comment]
This issue was fixed with PR #49.
