### ISSUE TITLE
How to get object through stenciljs routes

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/stencil-router#53]
_From @kchetans on June 4, 2018 11:13_

I was trying to pass data through stencils routes

e.g...
    this.history.push(`/detail`,{detail_data:docs});
    when I check their interface I found 
       push: (path: string | LocationSegments, state?: any) => void;
      so my object is state how would I access these object to /detail page
      I tried
      Prop() detail_data: object;
      but it's not working

_Copied from original issue: ionic-team/stencil#836_

**Comment by jthoms1** [comment]
You can actually access it through `history.location.state`

Here is an example in the codebase.
https://github.com/ionic-team/stencil-router/blob/master/src/components/__tests__/test-demo-three.tsx#L40

```jsx
@Component({
  tag: 'test-demo-three'
})
export class TestDemoThree {
  @Prop() history: RouterHistory;

  render() {
    return (
      <div>{history.location.state}</div>
    );
  }
}
```

**Comment by MoAsmar** [comment]
I suppose you mean `{this.history.location.state}`
