### ISSUE TITLE
Why stencil router is web components library?

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/stencil-router#54]
I wonder why this package is based on web components and not on pure js

I mean, it could nice js package that you import in your js file and use functions and config with object instead of using html tags
It's kinda confusing

Can someone explain me why web component is better than pure js plugin?

**Comment by jthoms1** [comment]
This router was created as a companion to the stenciljs web component compiler.

If you question is why web components this might answer that: https://www.webcomponents.org/community/articles/why-web-components

If you then wonder why Stencil, this should answer that:
https://stenciljs.com/docs/introduction

If it is specific to the configuration, I personally see that React Router was much nicer to use than something like UI router.  Imbedded routes are easier to follow through and application tree. This project was largely inspired by the React Router API.
