### ISSUE TITLE
Using anchors with scrollTopOffset breaks

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil-router#56]
Using anchors to link to different sections of the same page as we do [here](https://github.com/ionic-team/stencil-site/blob/master/src/docs-content/reference/decorators.html#L5) along with `scrollTopOffset` breaks. When you click on the anchor tag it tries to scroll down but the `scrollTopOffset` logic takes over and scrolls the page back to the top.

**Comment by jthoms1** [comment]
Fixed with commit 07bf942add0a645803c66fdbcf4676e85cce6bbe
