### ISSUE TITLE
Nested <stencil-route> not working

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil-router#57]
**Stencil version:**
```
 @stencil/core@0.10.0-11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Clicking a link pointing to a route that was just loaded from an already routed parent component makes the browser do a full postback.

**Expected behavior:**
Stencil app detects "lazy loaded" routes and does client side routing as with intiially loaded routes.

**Steps to reproduce:**
See repo:
https://github.com/bitflower/stencil-nested-routes

**Comment by bitflower** [comment]
My bad.... had a normal `<a>` link. Embarrasing me...

Now that it works: Stencil so rocks !! 

;-)

**Comment by newtonmunene99** [comment]
@bitflower  I'm trying to figure out how  nested routes work. Could you share the repo again.

**Comment by bitflower** [comment]
No longer online, sorry.

It's easy however:
1. place a <stencil-route> in an already routed component and the route will be avilable as soon as this component gets loaded. 
2. Link to these dynamically loaded routes with a <stencil-route-link>

My mistake was using a regular <a> in the beginning... which doesn't work.
