### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by John0x** [ionic-team/stencil-router#59]
Has there been a discussion about supporting event hooks for the Router?

They would be kinda handy in cases like a progressbar, that changes when you change the route to indicate the loading of a page. 

Events I'm thinking of:
- onRouteChangeStart 
- onRouteChangeComplete 
- onRouteChangeError 

Does anything speak against it? I'd be willing to implement it myself and create a PR. Just not sure if it fits with the existing API.

**Comment by jthoms1** [comment]
We have talked about it and decided not to support an event system.  This can all be accomplished today by watching the location change which gets passed down as a prop.

I would actually think the better way to track the progressbar would be an application wide state attribute that would be updated as you move through steps.

**Comment by daftclaud** [comment]
@jthoms1 could you post an example doing that (watching the location change which gets passed down as a prop)?

**Comment by JEricaM** [comment]
I think too that have an example should be nice :)

**Comment by mariospas** [comment]
if I have a navigation menu in app-root but I want to disable some parts in contact-page, how can I do it with stencil-router props ? Can you provide an example ?
