### ISSUE TITLE
Active link class not getting removed on sub-routes

### ISSUE THREAD

**Issue by mhartington** [ionic-team/stencil-router#6]
If a two routes share a similar path, the active link class will be applied to both.
This can be seen in the stencil-site repo.
Here, the active component is the demo page, but both the docs and demo link are marked as "active"

![screen shot 2017-08-31 at 2 46 13 pm](https://user-images.githubusercontent.com/2835826/29939814-2748b210-8e5b-11e7-8c90-5dbfc1d20a19.png)

Note, the landing Component's url is `/` and the demo component is `/demo` so that shared `/` is throwing things off. You can also see this as you navigate along the side menu links .

**Comment by jthoms1** [comment]
We now have `exact={true}` as an option.  This allows for some interesting link options.
