### ISSUE TITLE
Page-specific index.html not generated in www causing flicker when refreshed

### ISSUE THREAD

**Issue by gusterwoei-veltra** [ionic-team/stencil-router#60]
**What happened?**
Imagine I have 2 routes:
```
<stencil-route url='/areas' component='area-list-page' />
<stencil-route url='/activities' component='activity-list-page' />                            
```

Somewhere in the code, I have specified `<stencil-route-link>` for path `/areas` but not `/activities` (it will be routed programmatically instead).

When I run `npm run build`, stencil will generate `www/areas/index.html` but not `www/activities/index.html`

**Problem**
When I deploy `www` to a server (eg. firebase), visiting `/activities` and try to refresh it, you can notice a slight flicker between the page in `/` and `/activities`. This however won't happen if I have `www/activities/index.html` generated in `www`

**stencil.config.js**
```
const sass = require('@stencil/sass')

exports.config = {
    globalStyle: 'src/global/app.css',
    plugins: [
        sass()
    ],
    outputTargets: [
        {
            type: 'www',
            serviceWorker: {
                swSrc: 'src/sw.js',
                globPatterns: [
                    '**/*.{html,js,css,scss.json,ico,png,jpg}'
                ]
            }
        }
    ]
};

exports.devServer = {
    root: 'www',
    watchGlob: '**/**'
};
```

**Comment by jthoms1** [comment]
Are you using the `stencil-route-switch` component around the two routes? Also do you have this published live somewhere that I could run dev-tools against it?

**Comment by gusterwoei-veltra** [comment]
Both routes are wrapped within `stencil-route-switch`

You can try it here:

**The one with flicker:**
[https://testagent-670d9.firebaseapp.com](https://testagent-670d9.firebaseapp.com)

**The one without flicker:**
[https://pwa-demo-123.firebaseapp.com](https://pwa-demo-123.firebaseapp.com)

In both site, click `GETTING STARTED` button to go to `/repos` route, then try to refresh from there.

**Comment by jthoms1** [comment]
We have an undocumented config that would solve this exact problem.
Add prerenderLocations with a list of urls to your outputTarget.

   outputTargets: [
      {
         type: 'www',
         prerenderLocations: [
          { path: '/repos' }
         ],
         serviceWorker: {
            swSrc: 'src/sw.js',
            globPatterns: [
               '**/*.{js,css,json,html,ico,png}'
            ]
         }
      }
   ],
