### ISSUE TITLE
Stencil route not working in IE11

### ISSUE THREAD

**Issue by marisaoliva** [ionic-team/stencil-router#64]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```Stencil 10.2 stencil-route 0.2.2
 insert the output from npm list @stencil/core here
```

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
The problem is that the stencil-route  in IE 11 does not work, when you click to stencil-route-link the page does not show and the page is shown in white.

We can proove in yout  stencil-site (https://stenciljs.com/demos) 

![stencilsite](https://user-images.githubusercontent.com/3691725/44283787-bfe74e00-a25f-11e8-8a98-8bfcb2ca74a8.png)

**Other information:**

**Comment by marisaoliva** [comment]
Any progress with this issue?, I work with stencil-route in a project in production and I need to know if it has solution soon or I do a provisional workaround
Thanks!!

**Comment by jthoms1** [comment]
Working on a release today

**Comment by marisaoliva** [comment]
any progress with this? 

I'm sorry for insisting but it's important for my project, can you give me some release date?

**Comment by jthoms1** [comment]
Could you give the latest release a try?  I found an issue that fixed firefox.

@stencil/router@0.2.6

**Comment by marisaoliva** [comment]
I try in ie11 and not working yet, sorry

**Comment by jthoms1** [comment]
thanks, just grabbed a windows machine to try it out.

**Comment by marisaoliva** [comment]
any idea?

**Comment by marisaoliva** [comment]
any progress?? :D

**Comment by jthoms1** [comment]
Fixed with commit eefb15661ff39a72661ba54f6bbb64fc64ad8961. Released with 0.2.7.
