### ISSUE TITLE
Run from local sources

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil-router#65]
Would like to understand how do you test locally using the demo : 

i always got error : 

[ ERROR ]  Unresolved Import
           Could not resolve './components' from ../router/dist/collection/index.js 

Steps : 

npm i (a root)
lerna bootstrap 

/packages/router  
   npm run build 

/packages/demo 
 npm run build 

And cannot see the demo working.

I would like to help if i can understand the workflow you use for development of this component

**Comment by romulocintra** [comment]
I made demo work by deleting the export * from “components/“ , but still not understanding why

**Comment by jthoms1** [comment]
@romulocintra this is an issue with Stencil that will be resolved when 0.12.0 releases. Thanks!
