### ISSUE TITLE
"...style.display = null" doesn't work in IE11

### ISSUE THREAD

**Issue by victorgtp** [ionic-team/stencil-router#68]
https://github.com/ionic-team/stencil-router/blob/f936ef80cabc5e9a5e05e5b6c59e6a8d560760bc/packages/router/src/components/switch/switch.tsx#L103

Could you change it and put "...style.display = ''" or "...style.display = 'block' ?

Thanks!

**Comment by jthoms1** [comment]
Most likely related to the issue of #64

**Comment by jthoms1** [comment]
Fixed with commit eefb15661ff39a72661ba54f6bbb64fc64ad8961. Released with 0.2.7.

**Comment by marisaoliva** [comment]
thanks @victorgtp :)
