### ISSUE TITLE
Root prop incompatible with exact route matching

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/stencil-router#80]
```
@stencil/core@0.16.0
@stencil/router@0.3.1
```

---

Using the `root` property on `<stencil-router>` appears to break exact route matching. In this scenario, the first route will not match for the URL `/docs/`:

```html
<stencil-router root="/docs">
  <stencil-route-switch>
    <stencil-route url="/" exact .../>
    <stencil-route url="/foo" .../>
    <stencil-route url="/bar" .../>
  </stencil-route-switch>
</stencil-router>
```

Whereas all routes match correctly without `root`:

```html
<stencil-router>
  <stencil-route-switch>
    <stencil-route url="/docs/" exact .../>
    <stencil-route url="/docs/foo" .../>
    <stencil-route url="/docs/bar" .../>
  </stencil-route-switch>
</stencil-router>
```

👋

**Comment by AkhmedovValikhan** [comment]
I think you have type in your example code, as swtich doesn't have root prop, maybe you meant router?

**Comment by camwiegert** [comment]
@AkhmedovValikhan Updated, thanks!

**Comment by nzav** [comment]
Any updates on this?

**Comment by FortinFred** [comment]
@camwiegert 

I'm having the same issue.  I've been able to make it work with a trailing '/' in the root attribute.

`root="/docs/"`

Issue seems to be coming from the `getLocation` function which will output a '//something' location when the root has no trailing '/'.

https://github.com/ionic-team/stencil-router/blob/228e1f3888759d651aa436ea3bfe5201e5872803/packages/router/src/components/router/router.tsx#L8
