### ISSUE TITLE
Builds break when using router elements in multiple components

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil-router#86]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.16.2
```

**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Using `stencil-route-link` and/or `stencil-route` in multiple components will break your production build:

```
[ ERROR ]  TypeError: Cannot read property 'toString' of undefined at e.getRenderedHash
           (@stencil/core/dist/sys/node/index.js:1:324262) at
           @stencil/core/dist/sys/node/index.js:1:325017 at
           e.visitDependencies (@stencil/core/dist/sys/node/index.js:1:324643)
           at e.computeContentHashWithDependencies
           (@stencil/core/dist/sys/node/index.js:1:324921) at
           @stencil/core/dist/sys/node/index.js:1:329531 at
           @stencil/core/dist/sys/node/index.js:1:313503 at String.replace
           (<anonymous>) at renderNamePattern
           (@stencil/core/dist/sys/node/index.js:1:313462) at e.generateId
           (@stencil/core/dist/sys/node/index.js:1:329417) at assignChunkIds
           (@stencil/core/dist/sys/node/index.js:1:455624)
```
**Expected behavior:**
You can sprinkle stencil-route components throughout your app and do a prod build with no issues.

**Steps to reproduce:**
- `npm init stencil`
- _cd into project dir_
- `npm run-script build`
- 💥 

**Related code:**
If you edit the newly created project's `app-home.tsx` and remove the stencil-route-link it will build again.

```
insert any relevant code here
```

**Other information:**
This is the source of the following issue in core: https://github.com/ionic-team/stencil/issues/1313

**Comment by simonhaenisch** [comment]
This is pretty much the same as https://github.com/ionic-team/stencil/issues/1306 which was a Stencil issue (actually an upstream issue with Rollup) that should be fixed in `0.17.0-0` (`npm install @stencil/core@next`), if you want to try it out.
