### ISSUE TITLE
Router Redirect is not working

### ISSUE THREAD

**Issue by bfmatei** [ionic-team/stencil-router#9]
As the title says, stencil-route-redirect is not working.

Versions: core, router and dev-server are set to "next" while utils are set to "latest".

```html
<stencil-route url="/" exact="true">
  <stencil-route-redirect url="/another-path" />
</stencil-route>
<stencil-route url="/another-path" component="app-component" />
```

Regards,
Bogdan

**Comment by jthoms1** [comment]
The actual name of the redirect is 'stencil-router-redirect'. Here is an example: https://github.com/ionic-team/stencil-router/blob/master/src/components/__tests__/test-app.tsx#L42

**Comment by ntregillus** [comment]
link no longer works.

I am attempting to use `stencil-route-redirect` in my render to cause the router to go to my 403 page when a wrapping component checks permissions.... it just doesn't work....

**Comment by FortinFred** [comment]
Should be reopened as a documentation bug since the Wiki refers to the component as "stencil-route-redirect"

https://github.com/ionic-team/stencil-router/wiki/stencil-route-redirect
